; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30723.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG4455	DB	0aH, 'Found 2 in list.', 00H
	ORG $+6
$SG4457	DB	0aH, 'Not found 2 in list.', 00H
	ORG $+2
$SG4459	DB	0aH, 'Found 4 in list.', 00H
	ORG $+6
$SG4461	DB	0aH, 'Not found 4 in list.', 00H
	ORG $+2
$SG4464	DB	0aH, 'Deleted first 2.', 00H
	ORG $+6
$SG4466	DB	0aH, 'Deleted first 4.', 00H
	ORG $+6
$SG4468	DB	0aH, '4 Not found.', 00H
	ORG $+2
$SG4470	DB	0aH, 'Deleted first 1.', 00H
	ORG $+6
$SG4472	DB	0aH, '1 Not found.', 00H
	ORG $+2
$SG4476	DB	0aH, 'All 2s deleted from list.', 00H
	ORG $+5
$SG4478	DB	0aH, '2 not found.', 00H
_DATA	ENDS
PUBLIC	TEST_setup1
PUBLIC	TEST_search1
PUBLIC	TEST_delete1
PUBLIC	TEST_delete2
EXTRN	printf:PROC
EXTRN	add_to_list:PROC
EXTRN	print_list:PROC
EXTRN	search_list:PROC
EXTRN	delete_first_value_matching_node:PROC
EXTRN	delete_all_value_matching_nodes:PROC
pdata	SEGMENT
$pdata$TEST_setup1 DD imagerel $LN3
	DD	imagerel $LN3+74
	DD	imagerel $unwind$TEST_setup1
$pdata$TEST_search1 DD imagerel $LN7
	DD	imagerel $LN7+95
	DD	imagerel $unwind$TEST_search1
$pdata$TEST_delete1 DD imagerel $LN8
	DD	imagerel $LN8+149
	DD	imagerel $unwind$TEST_delete1
$pdata$TEST_delete2 DD imagerel $LN5
	DD	imagerel $LN5+57
	DD	imagerel $unwind$TEST_delete2
pdata	ENDS
xdata	SEGMENT
$unwind$TEST_setup1 DD 010401H
	DD	04204H
$unwind$TEST_search1 DD 010401H
	DD	04204H
$unwind$TEST_delete1 DD 010401H
	DD	04204H
$unwind$TEST_delete2 DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
TEST_delete2 PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 49
$LN5:
	sub	rsp, 40					; 00000028H
; Line 50
	mov	ecx, 2
	call	delete_all_value_matching_nodes
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_delet
; Line 51
	lea	rcx, OFFSET FLAT:$SG4476
	call	printf
; Line 53
	jmp	SHORT $LN1@TEST_delet
$LN2@TEST_delet:
; Line 54
	lea	rcx, OFFSET FLAT:$SG4478
	call	printf
$LN1@TEST_delet:
; Line 56
	call	print_list
; Line 57
	add	rsp, 40					; 00000028H
	ret	0
TEST_delete2 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
TEST_delete1 PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 18
$LN8:
	sub	rsp, 40					; 00000028H
; Line 19
	mov	ecx, 2
	call	delete_first_value_matching_node
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN5@TEST_delet
; Line 20
	lea	rcx, OFFSET FLAT:$SG4464
	call	printf
; Line 21
	call	print_list
$LN5@TEST_delet:
; Line 23
	mov	ecx, 4
	call	delete_first_value_matching_node
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN4@TEST_delet
; Line 24
	lea	rcx, OFFSET FLAT:$SG4466
	call	printf
; Line 25
	call	print_list
; Line 27
	jmp	SHORT $LN3@TEST_delet
$LN4@TEST_delet:
; Line 28
	lea	rcx, OFFSET FLAT:$SG4468
	call	printf
; Line 29
	call	print_list
$LN3@TEST_delet:
; Line 31
	mov	ecx, 1
	call	delete_first_value_matching_node
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_delet
; Line 32
	lea	rcx, OFFSET FLAT:$SG4470
	call	printf
; Line 33
	call	print_list
; Line 35
	jmp	SHORT $LN1@TEST_delet
$LN2@TEST_delet:
; Line 36
	lea	rcx, OFFSET FLAT:$SG4472
	call	printf
; Line 37
	call	print_list
$LN1@TEST_delet:
; Line 39
	add	rsp, 40					; 00000028H
	ret	0
TEST_delete1 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
TEST_search1 PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 3
$LN7:
	sub	rsp, 40					; 00000028H
; Line 4
	mov	ecx, 2
	call	search_list
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN4@TEST_searc
; Line 5
	lea	rcx, OFFSET FLAT:$SG4455
	call	printf
; Line 7
	jmp	SHORT $LN3@TEST_searc
$LN4@TEST_searc:
; Line 8
	lea	rcx, OFFSET FLAT:$SG4457
	call	printf
$LN3@TEST_searc:
; Line 10
	mov	ecx, 4
	call	search_list
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_searc
; Line 11
	lea	rcx, OFFSET FLAT:$SG4459
	call	printf
; Line 13
	jmp	SHORT $LN1@TEST_searc
$LN2@TEST_searc:
; Line 14
	lea	rcx, OFFSET FLAT:$SG4461
	call	printf
$LN1@TEST_searc:
; Line 16
	add	rsp, 40					; 00000028H
	ret	0
TEST_search1 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
TEST_setup1 PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 41
$LN3:
	sub	rsp, 40					; 00000028H
; Line 42
	xor	edx, edx
	mov	ecx, 1
	call	add_to_list
; Line 43
	xor	edx, edx
	mov	ecx, 2
	call	add_to_list
; Line 44
	xor	edx, edx
	mov	ecx, 3
	call	add_to_list
; Line 45
	mov	dl, 1
	mov	ecx, 8
	call	add_to_list
; Line 46
	xor	edx, edx
	mov	ecx, 2
	call	add_to_list
; Line 47
	call	print_list
; Line 48
	add	rsp, 40					; 00000028H
	ret	0
TEST_setup1 ENDP
_TEXT	ENDS
END
