; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30723.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG4484	DB	0aH, 'Found %d in list.', 00H
	ORG $+5
$SG4486	DB	0aH, 'Did not find %d in list.', 00H
	ORG $+6
$SG4491	DB	0aH, 'Found %d in list.', 00H
	ORG $+5
$SG4493	DB	0aH, 'Did not find %d in list.', 00H
	ORG $+6
$SG4498	DB	0aH, 'Deleted first %d.', 00H
	ORG $+5
$SG4500	DB	0aH, 'Deleted first %d.', 00H
	ORG $+5
$SG4502	DB	0aH, 'Did not find %d in list.', 00H
	ORG $+6
$SG4504	DB	0aH, 'Deleted first %d.', 00H
	ORG $+5
$SG4506	DB	0aH, 'Did not find %d in list.', 00H
	ORG $+6
$SG4516	DB	0aH, 'All %d deleted from list.', 00H
	ORG $+5
$SG4518	DB	0aH, 'Did not find %d in list.', 00H
	ORG $+6
$SG4521	DB	0aH, 'Circular list test: list should not be circular.', 00H
	ORG $+6
$SG4523	DB	0aH, 'list is circular.', 00H
	ORG $+5
$SG4525	DB	0aH, 'list is not circular.', 00H
	ORG $+1
$SG4528	DB	0aH, 'Circular list test: list should be circular.', 00H
	ORG $+2
$SG4530	DB	0aH, 'list is circular.', 00H
	ORG $+5
$SG4532	DB	0aH, 'list is not circular.', 00H
_DATA	ENDS
PUBLIC	TEST_should_setup_and_confim_via_printing
PUBLIC	TEST_should_find_number_in_list
PUBLIC	TEST_should_not_find_number_in_list
PUBLIC	TEST_should_delete_numbers_first_occurence
PUBLIC	TEST_should_delete_all_occurences_on_a_number
PUBLIC	TEST_shoud_not_be_a_circular_list
PUBLIC	TEST_shoud_be_a_circular_list
EXTRN	printf:PROC
EXTRN	add_to_list:PROC
EXTRN	make_list_circular:PROC
EXTRN	print_list:PROC
EXTRN	search_list:PROC
EXTRN	delete_first_value_matching_node:PROC
EXTRN	delete_all_value_matching_nodes:PROC
EXTRN	is_list_circular:PROC
pdata	SEGMENT
$pdata$TEST_should_setup_and_confim_via_printing DD imagerel $LN3
	DD	imagerel $LN3+177
	DD	imagerel $unwind$TEST_should_setup_and_confim_via_printing
$pdata$TEST_should_find_number_in_list DD imagerel $LN5
	DD	imagerel $LN5+82
	DD	imagerel $unwind$TEST_should_find_number_in_list
$pdata$TEST_should_not_find_number_in_list DD imagerel $LN5
	DD	imagerel $LN5+82
	DD	imagerel $unwind$TEST_should_not_find_number_in_list
$pdata$TEST_should_delete_numbers_first_occurence DD imagerel $LN8
	DD	imagerel $LN8+241
	DD	imagerel $unwind$TEST_should_delete_numbers_first_occurence
$pdata$TEST_should_delete_all_occurences_on_a_number DD imagerel $LN5
	DD	imagerel $LN5+92
	DD	imagerel $unwind$TEST_should_delete_all_occurences_on_a_number
$pdata$TEST_shoud_not_be_a_circular_list DD imagerel $LN5
	DD	imagerel $LN5+84
	DD	imagerel $unwind$TEST_shoud_not_be_a_circular_list
$pdata$TEST_shoud_be_a_circular_list DD imagerel $LN5
	DD	imagerel $LN5+104
	DD	imagerel $unwind$TEST_shoud_be_a_circular_list
pdata	ENDS
xdata	SEGMENT
$unwind$TEST_should_setup_and_confim_via_printing DD 010401H
	DD	06204H
$unwind$TEST_should_find_number_in_list DD 010401H
	DD	06204H
$unwind$TEST_should_not_find_number_in_list DD 010401H
	DD	06204H
$unwind$TEST_should_delete_numbers_first_occurence DD 010401H
	DD	06204H
$unwind$TEST_should_delete_all_occurences_on_a_number DD 010401H
	DD	06204H
$unwind$TEST_shoud_not_be_a_circular_list DD 010401H
	DD	06204H
$unwind$TEST_shoud_be_a_circular_list DD 010401H
	DD	06204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
head$ = 32
TEST_shoud_be_a_circular_list PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 90
$LN5:
	sub	rsp, 56					; 00000038H
; Line 91
	call	TEST_should_setup_and_confim_via_printing
	mov	QWORD PTR head$[rsp], rax
; Line 92
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 93
	mov	rcx, QWORD PTR head$[rsp]
	call	make_list_circular
; Line 95
	lea	rcx, OFFSET FLAT:$SG4528
	call	printf
; Line 96
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 97
	mov	rcx, QWORD PTR head$[rsp]
	call	is_list_circular
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_shoud
; Line 98
	lea	rcx, OFFSET FLAT:$SG4530
	call	printf
; Line 100
	jmp	SHORT $LN1@TEST_shoud
$LN2@TEST_shoud:
; Line 101
	lea	rcx, OFFSET FLAT:$SG4532
	call	printf
$LN1@TEST_shoud:
; Line 103
	add	rsp, 56					; 00000038H
	ret	0
TEST_shoud_be_a_circular_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
head$ = 32
TEST_shoud_not_be_a_circular_list PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 77
$LN5:
	sub	rsp, 56					; 00000038H
; Line 78
	call	TEST_should_setup_and_confim_via_printing
	mov	QWORD PTR head$[rsp], rax
; Line 79
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 80
	lea	rcx, OFFSET FLAT:$SG4521
	call	printf
; Line 81
	mov	rcx, QWORD PTR head$[rsp]
	call	is_list_circular
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_shoud
; Line 82
	lea	rcx, OFFSET FLAT:$SG4523
	call	printf
; Line 84
	jmp	SHORT $LN1@TEST_shoud
$LN2@TEST_shoud:
; Line 85
	lea	rcx, OFFSET FLAT:$SG4525
	call	printf
$LN1@TEST_shoud:
; Line 87
	add	rsp, 56					; 00000038H
	ret	0
TEST_shoud_not_be_a_circular_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
num$ = 32
head$ = 40
TEST_should_delete_all_occurences_on_a_number PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 65
$LN5:
	sub	rsp, 56					; 00000038H
; Line 66
	call	TEST_should_setup_and_confim_via_printing
	mov	QWORD PTR head$[rsp], rax
; Line 67
	mov	DWORD PTR num$[rsp], 2
; Line 68
	mov	edx, DWORD PTR num$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	delete_all_value_matching_nodes
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_shoul
; Line 69
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4516
	call	printf
; Line 71
	jmp	SHORT $LN1@TEST_shoul
$LN2@TEST_shoul:
; Line 72
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4518
	call	printf
$LN1@TEST_shoul:
; Line 74
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 75
	add	rsp, 56					; 00000038H
	ret	0
TEST_should_delete_all_occurences_on_a_number ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
num$ = 32
head$ = 40
TEST_should_delete_numbers_first_occurence PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 26
$LN8:
	sub	rsp, 56					; 00000038H
; Line 27
	call	TEST_should_setup_and_confim_via_printing
	mov	QWORD PTR head$[rsp], rax
; Line 28
	mov	DWORD PTR num$[rsp], 2
; Line 29
	mov	edx, DWORD PTR num$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	delete_first_value_matching_node
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN5@TEST_shoul
; Line 30
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4498
	call	printf
; Line 31
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
$LN5@TEST_shoul:
; Line 33
	mov	DWORD PTR num$[rsp], 4
; Line 34
	mov	edx, DWORD PTR num$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	delete_first_value_matching_node
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN4@TEST_shoul
; Line 35
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4500
	call	printf
; Line 36
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 38
	jmp	SHORT $LN3@TEST_shoul
$LN4@TEST_shoul:
; Line 39
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4502
	call	printf
; Line 40
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
$LN3@TEST_shoul:
; Line 42
	mov	DWORD PTR num$[rsp], 1
; Line 43
	mov	edx, 1
	mov	rcx, QWORD PTR head$[rsp]
	call	delete_first_value_matching_node
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_shoul
; Line 44
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4504
	call	printf
; Line 45
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 47
	jmp	SHORT $LN1@TEST_shoul
$LN2@TEST_shoul:
; Line 48
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4506
	call	printf
; Line 49
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
$LN1@TEST_shoul:
; Line 51
	add	rsp, 56					; 00000038H
	ret	0
TEST_should_delete_numbers_first_occurence ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
num$ = 32
head$ = 40
TEST_should_not_find_number_in_list PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 15
$LN5:
	sub	rsp, 56					; 00000038H
; Line 16
	call	TEST_should_setup_and_confim_via_printing
	mov	QWORD PTR head$[rsp], rax
; Line 17
	mov	DWORD PTR num$[rsp], 4
; Line 18
	mov	edx, DWORD PTR num$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	search_list
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_shoul
; Line 19
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4491
	call	printf
; Line 21
	jmp	SHORT $LN1@TEST_shoul
$LN2@TEST_shoul:
; Line 22
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4493
	call	printf
$LN1@TEST_shoul:
; Line 24
	add	rsp, 56					; 00000038H
	ret	0
TEST_should_not_find_number_in_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
num$ = 32
head$ = 40
TEST_should_find_number_in_list PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 3
$LN5:
	sub	rsp, 56					; 00000038H
; Line 4
	call	TEST_should_setup_and_confim_via_printing
	mov	QWORD PTR head$[rsp], rax
; Line 5
	mov	DWORD PTR num$[rsp], 2
; Line 6
	mov	edx, DWORD PTR num$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	search_list
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@TEST_shoul
; Line 7
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4484
	call	printf
; Line 9
	jmp	SHORT $LN1@TEST_shoul
$LN2@TEST_shoul:
; Line 10
	mov	edx, DWORD PTR num$[rsp]
	lea	rcx, OFFSET FLAT:$SG4486
	call	printf
$LN1@TEST_shoul:
; Line 13
	add	rsp, 56					; 00000038H
	ret	0
TEST_should_find_number_in_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
head$ = 32
curr$ = 40
TEST_should_setup_and_confim_via_printing PROC
; File c:\src\blog posts\linked lists\integer linked list test.c
; Line 53
$LN3:
	sub	rsp, 56					; 00000038H
; Line 54
	mov	QWORD PTR head$[rsp], 0
; Line 55
	mov	QWORD PTR curr$[rsp], 0
; Line 56
	xor	r9d, r9d
	mov	r8d, 1
	mov	rdx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	add_to_list
	mov	QWORD PTR curr$[rsp], rax
	mov	rax, QWORD PTR curr$[rsp]
	mov	QWORD PTR head$[rsp], rax
; Line 57
	xor	r9d, r9d
	mov	r8d, 2
	mov	rdx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	add_to_list
; Line 58
	xor	r9d, r9d
	mov	r8d, 3
	mov	rdx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	add_to_list
; Line 59
	mov	r9b, 1
	mov	r8d, 8
	mov	rdx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	add_to_list
; Line 60
	xor	r9d, r9d
	mov	r8d, 2
	mov	rdx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	call	add_to_list
; Line 61
	mov	rcx, QWORD PTR head$[rsp]
	call	print_list
; Line 62
	mov	rax, QWORD PTR head$[rsp]
; Line 63
	add	rsp, 56					; 00000038H
	ret	0
TEST_should_setup_and_confim_via_printing ENDP
_TEXT	ENDS
END
