; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30723.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	head
PUBLIC	curr
_BSS	SEGMENT
head	DQ	01H DUP (?)
curr	DQ	01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
$SG4479	DB	0aH, 'Circular list.', 00H
$SG4483	DB	0aH, 'The values of the list are : ', 00H
	ORG $+1
$SG4487	DB	' [%d]-> ', 00H
	ORG $+7
$SG4488	DB	'[NULL]', 0aH, 00H
$SG4490	DB	0aH, 'Empty list.', 00H
_DATA	ENDS
PUBLIC	create_list
PUBLIC	add_to_list
PUBLIC	make_list_circular
PUBLIC	print_list
PUBLIC	search_list
PUBLIC	delete_first_value_matching_node
PUBLIC	delete_all_value_matching_nodes
PUBLIC	is_list_empty
PUBLIC	is_list_circular
EXTRN	printf:PROC
EXTRN	abort:PROC
EXTRN	malloc:PROC
pdata	SEGMENT
$pdata$create_list DD imagerel $LN4
	DD	imagerel $LN4+96
	DD	imagerel $unwind$create_list
$pdata$add_to_list DD imagerel $LN6
	DD	imagerel $LN6+173
	DD	imagerel $unwind$add_to_list
$pdata$make_list_circular DD imagerel $LN5
	DD	imagerel $LN5+67
	DD	imagerel $unwind$make_list_circular
$pdata$print_list DD imagerel $LN9
	DD	imagerel $LN9+141
	DD	imagerel $unwind$print_list
$pdata$search_list DD imagerel $LN6
	DD	imagerel $LN6+76
	DD	imagerel $unwind$search_list
$pdata$delete_first_value_matching_node DD imagerel $LN9
	DD	imagerel $LN9+177
	DD	imagerel $unwind$delete_first_value_matching_node
$pdata$delete_all_value_matching_nodes DD imagerel $LN9
	DD	imagerel $LN9+169
	DD	imagerel $unwind$delete_all_value_matching_nodes
$pdata$is_list_circular DD imagerel $LN6
	DD	imagerel $LN6+118
	DD	imagerel $unwind$is_list_circular
pdata	ENDS
xdata	SEGMENT
$unwind$create_list DD 010801H
	DD	06208H
$unwind$add_to_list DD 010c01H
	DD	0620cH
$unwind$make_list_circular DD 010401H
	DD	02204H
$unwind$print_list DD 010401H
	DD	06204H
$unwind$search_list DD 010801H
	DD	02208H
$unwind$delete_first_value_matching_node DD 010801H
	DD	04208H
$unwind$delete_all_value_matching_nodes DD 010801H
	DD	04208H
$unwind$is_list_circular DD 010401H
	DD	02204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
fast$ = 0
slow$ = 8
is_list_circular PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 161
$LN6:
	sub	rsp, 24
; Line 162
	mov	rax, QWORD PTR head
	mov	QWORD PTR slow$[rsp], rax
; Line 163
	mov	rax, QWORD PTR head
	mov	QWORD PTR fast$[rsp], rax
$LN3@is_list_ci:
; Line 164
	cmp	QWORD PTR slow$[rsp], 0
	je	SHORT $LN2@is_list_ci
	cmp	QWORD PTR fast$[rsp], 0
	je	SHORT $LN2@is_list_ci
	mov	rax, QWORD PTR fast$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN2@is_list_ci
	mov	rax, QWORD PTR fast$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN2@is_list_ci
; Line 165
	mov	rax, QWORD PTR fast$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR fast$[rsp], rax
; Line 166
	mov	rax, QWORD PTR slow$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR slow$[rsp], rax
; Line 167
	mov	rax, QWORD PTR fast$[rsp]
	cmp	QWORD PTR slow$[rsp], rax
	jne	SHORT $LN1@is_list_ci
; Line 168
	mov	al, 1
	jmp	SHORT $LN4@is_list_ci
$LN1@is_list_ci:
; Line 170
	jmp	SHORT $LN3@is_list_ci
$LN2@is_list_ci:
; Line 171
	xor	al, al
$LN4@is_list_ci:
; Line 172
	add	rsp, 24
	ret	0
is_list_circular ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
is_list_empty PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 175
	cmp	QWORD PTR head, 0
	jne	SHORT $LN2@is_list_em
; Line 176
	mov	al, 1
	jmp	SHORT $LN3@is_list_em
; Line 177
	jmp	SHORT $LN1@is_list_em
$LN2@is_list_em:
; Line 178
	xor	al, al
$LN1@is_list_em:
$LN3@is_list_em:
; Line 179
	ret	0
is_list_empty ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
isDeleted$ = 0
curr$ = 8
prev$ = 16
val$ = 48
delete_all_value_matching_nodes PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 136
$LN9:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 40					; 00000028H
; Line 137
	mov	rax, QWORD PTR head
	mov	QWORD PTR prev$[rsp], rax
; Line 138
	mov	QWORD PTR curr$[rsp], 0
; Line 139
	mov	BYTE PTR isDeleted$[rsp], 0
; Line 140
	mov	rax, QWORD PTR head
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN6@delete_all
; Line 141
	mov	rax, QWORD PTR head
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
$LN5@delete_all:
; Line 142
	cmp	QWORD PTR curr$[rsp], 0
	je	SHORT $LN4@delete_all
; Line 143
	mov	rax, QWORD PTR curr$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN3@delete_all
; Line 144
	mov	BYTE PTR isDeleted$[rsp], 1
; Line 145
	mov	rax, QWORD PTR prev$[rsp]
	mov	rcx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax+8], rcx
$LN3@delete_all:
; Line 148
	mov	rax, QWORD PTR curr$[rsp]
	mov	QWORD PTR prev$[rsp], rax
; Line 149
	mov	rax, QWORD PTR curr$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
; Line 150
	jmp	SHORT $LN5@delete_all
$LN4@delete_all:
; Line 152
	jmp	SHORT $LN2@delete_all
$LN6@delete_all:
; Line 153
	mov	rax, QWORD PTR prev$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN1@delete_all
; Line 154
	mov	BYTE PTR isDeleted$[rsp], 1
; Line 155
	mov	QWORD PTR prev$[rsp], 0
$LN1@delete_all:
$LN2@delete_all:
; Line 158
	movzx	eax, BYTE PTR isDeleted$[rsp]
; Line 159
	add	rsp, 40					; 00000028H
	ret	0
delete_all_value_matching_nodes ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
isDeleted$ = 0
curr$ = 8
prev$ = 16
val$ = 48
delete_first_value_matching_node PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 104
$LN9:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 40					; 00000028H
; Line 105
	mov	rax, QWORD PTR head
	mov	QWORD PTR prev$[rsp], rax
; Line 106
	mov	QWORD PTR curr$[rsp], 0
; Line 107
	mov	BYTE PTR isDeleted$[rsp], 0
; Line 108
	mov	rax, QWORD PTR head
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN6@delete_fir
; Line 109
	mov	rax, QWORD PTR head
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
$LN5@delete_fir:
; Line 113
	cmp	QWORD PTR curr$[rsp], 0
	je	SHORT $LN4@delete_fir
	movzx	eax, BYTE PTR isDeleted$[rsp]
	test	eax, eax
	jne	SHORT $LN4@delete_fir
; Line 114
	mov	rax, QWORD PTR curr$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN3@delete_fir
; Line 115
	mov	rax, QWORD PTR prev$[rsp]
	mov	rcx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax+8], rcx
; Line 116
	mov	BYTE PTR isDeleted$[rsp], 1
$LN3@delete_fir:
; Line 119
	mov	rax, QWORD PTR curr$[rsp]
	mov	QWORD PTR prev$[rsp], rax
; Line 120
	mov	rax, QWORD PTR curr$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
; Line 121
	jmp	SHORT $LN5@delete_fir
$LN4@delete_fir:
; Line 123
	jmp	SHORT $LN2@delete_fir
$LN6@delete_fir:
; Line 127
	mov	rax, QWORD PTR prev$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN1@delete_fir
; Line 128
	mov	BYTE PTR isDeleted$[rsp], 1
; Line 130
	mov	QWORD PTR prev$[rsp], 0
$LN1@delete_fir:
$LN2@delete_fir:
; Line 133
	movzx	eax, BYTE PTR isDeleted$[rsp]
; Line 134
	add	rsp, 40					; 00000028H
	ret	0
delete_first_value_matching_node ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
isFound$ = 0
start$ = 8
val$ = 32
search_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 91
$LN6:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 92
	mov	rax, QWORD PTR head
	mov	QWORD PTR start$[rsp], rax
; Line 93
	mov	BYTE PTR isFound$[rsp], 0
$LN3@search_lis:
; Line 94
	cmp	QWORD PTR start$[rsp], 0
	je	SHORT $LN2@search_lis
; Line 95
	mov	rax, QWORD PTR start$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN1@search_lis
; Line 96
	mov	BYTE PTR isFound$[rsp], 1
; Line 97
	jmp	SHORT $LN2@search_lis
$LN1@search_lis:
; Line 99
	mov	rax, QWORD PTR start$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR start$[rsp], rax
; Line 100
	jmp	SHORT $LN3@search_lis
$LN2@search_lis:
; Line 101
	movzx	eax, BYTE PTR isFound$[rsp]
; Line 102
	add	rsp, 24
	ret	0
search_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 32
print_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 65
$LN9:
	sub	rsp, 56					; 00000038H
; Line 69
	mov	rax, QWORD PTR head
	mov	QWORD PTR ptr$[rsp], rax
; Line 70
	call	is_list_circular
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN6@print_list
; Line 71
	lea	rcx, OFFSET FLAT:$SG4479
	call	printf
; Line 73
	jmp	SHORT $LN5@print_list
$LN6@print_list:
; Line 74
	cmp	QWORD PTR ptr$[rsp], 0
	je	SHORT $LN4@print_list
; Line 75
	lea	rcx, OFFSET FLAT:$SG4483
	call	printf
$LN3@print_list:
; Line 76
	cmp	QWORD PTR ptr$[rsp], 0
	je	SHORT $LN2@print_list
; Line 77
	mov	r8, QWORD PTR ptr$[rsp]
	mov	rax, QWORD PTR ptr$[rsp]
	mov	edx, DWORD PTR [rax]
	lea	rcx, OFFSET FLAT:$SG4487
	call	printf
; Line 78
	mov	rax, QWORD PTR ptr$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR ptr$[rsp], rax
; Line 79
	jmp	SHORT $LN3@print_list
$LN2@print_list:
; Line 80
	lea	rcx, OFFSET FLAT:$SG4488
	call	printf
; Line 82
	jmp	SHORT $LN1@print_list
$LN4@print_list:
; Line 83
	lea	rcx, OFFSET FLAT:$SG4490
	call	printf
$LN1@print_list:
$LN5@print_list:
; Line 89
	add	rsp, 56					; 00000038H
	ret	0
print_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tmp$ = 0
make_list_circular PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 51
$LN5:
	sub	rsp, 24
; Line 55
	mov	rax, QWORD PTR head
	mov	QWORD PTR tmp$[rsp], rax
$LN2@make_list_:
; Line 56
	cmp	QWORD PTR tmp$[rsp], 0
	je	SHORT $LN1@make_list_
	mov	rax, QWORD PTR tmp$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN1@make_list_
; Line 57
	mov	rax, QWORD PTR tmp$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR tmp$[rsp], rax
; Line 58
	jmp	SHORT $LN2@make_list_
$LN1@make_list_:
; Line 59
	mov	rax, QWORD PTR tmp$[rsp]
	mov	rcx, QWORD PTR head
	mov	QWORD PTR [rax+8], rcx
; Line 63
	add	rsp, 24
	ret	0
make_list_circular ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
newTS$ = 32
val$ = 64
before_head$ = 72
add_to_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 24
$LN6:
	mov	BYTE PTR [rsp+16], dl
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 28
	mov	ecx, 16
	call	malloc
	mov	QWORD PTR newTS$[rsp], rax
; Line 29
	call	is_list_empty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN3@add_to_lis
; Line 30
	mov	ecx, DWORD PTR val$[rsp]
	call	create_list
	jmp	SHORT $LN4@add_to_lis
$LN3@add_to_lis:
; Line 33
	movzx	eax, BYTE PTR before_head$[rsp]
	test	eax, eax
	je	SHORT $LN2@add_to_lis
; Line 34
	mov	rax, QWORD PTR newTS$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	mov	DWORD PTR [rax], ecx
; Line 35
	mov	rax, QWORD PTR newTS$[rsp]
	mov	rcx, QWORD PTR head
	mov	QWORD PTR [rax+8], rcx
; Line 36
	mov	rax, QWORD PTR newTS$[rsp]
	mov	QWORD PTR head, rax
; Line 37
	mov	rax, QWORD PTR head
	jmp	SHORT $LN4@add_to_lis
; Line 39
	jmp	SHORT $LN1@add_to_lis
$LN2@add_to_lis:
; Line 40
	mov	rax, QWORD PTR newTS$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	mov	DWORD PTR [rax], ecx
; Line 41
	mov	rax, QWORD PTR newTS$[rsp]
	mov	QWORD PTR [rax+8], 0
; Line 42
	mov	rax, QWORD PTR curr
	mov	rcx, QWORD PTR newTS$[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 43
	mov	rax, QWORD PTR newTS$[rsp]
	mov	QWORD PTR curr, rax
; Line 44
	mov	rax, QWORD PTR curr
$LN1@add_to_lis:
$LN4@add_to_lis:
; Line 49
	add	rsp, 56					; 00000038H
	ret	0
add_to_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 32
val$ = 64
create_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 6
$LN4:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 10
	mov	ecx, 16
	call	malloc
	mov	QWORD PTR ptr$[rsp], rax
; Line 11
	cmp	QWORD PTR ptr$[rsp], 0
	jne	SHORT $LN1@create_lis
; Line 12
	call	abort
$LN1@create_lis:
; Line 14
	mov	rax, QWORD PTR ptr$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	mov	DWORD PTR [rax], ecx
; Line 15
	mov	rax, QWORD PTR ptr$[rsp]
	mov	QWORD PTR [rax+8], 0
; Line 17
	mov	rax, QWORD PTR ptr$[rsp]
	mov	QWORD PTR curr, rax
	mov	rax, QWORD PTR curr
	mov	QWORD PTR head, rax
; Line 18
	mov	rax, QWORD PTR ptr$[rsp]
$LN3@create_lis:
; Line 22
	add	rsp, 56					; 00000038H
	ret	0
create_list ENDP
_TEXT	ENDS
END
