; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30723.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG4471	DB	0aH, 'debug: entering create_node with value : %d.', 00H
	ORG $+2
$SG4478	DB	0aH, 'debug: exiting create_node.', 00H
	ORG $+3
$SG4484	DB	0aH, 'debug: entering add_to_list with value : %d.', 00H
	ORG $+2
$SG4491	DB	0aH, 'debug: exiting add_to_list.', 00H
	ORG $+3
$SG4495	DB	0aH, 'debug: entering make_list_circular.', 00H
	ORG $+3
$SG4500	DB	0aH, 'debug: exiting make_list_circular.', 00H
	ORG $+4
$SG4504	DB	0aH, 'debug: entering print_list.', 00H
	ORG $+3
$SG4507	DB	0aH, 'Circular list.', 00H
$SG4511	DB	0aH, 'The values of the list are : ', 00H
	ORG $+1
$SG4515	DB	' [%d]-> ', 00H
	ORG $+7
$SG4516	DB	'[NULL]', 0aH, 00H
$SG4518	DB	0aH, 'Empty list.', 00H
	ORG $+3
$SG4519	DB	0aH, 'debug: exiting print_list.', 00H
	ORG $+4
$SG4543	DB	0aH, 'debug: at least two nodes exists.', 00H
	ORG $+5
$SG4550	DB	0aH, 'debug: only one node exists.', 00H
_DATA	ENDS
PUBLIC	create_node
PUBLIC	add_to_list
PUBLIC	make_list_circular
PUBLIC	print_list
PUBLIC	search_list
PUBLIC	delete_first_value_matching_node
PUBLIC	delete_all_value_matching_nodes
PUBLIC	is_list_empty
PUBLIC	is_list_circular
PUBLIC	create_stack_from_existing_list
EXTRN	printf:PROC
EXTRN	abort:PROC
EXTRN	malloc:PROC
pdata	SEGMENT
$pdata$create_node DD imagerel $LN4
	DD	imagerel $LN4+100
	DD	imagerel $unwind$create_node
$pdata$add_to_list DD imagerel $LN5
	DD	imagerel $LN5+112
	DD	imagerel $unwind$add_to_list
$pdata$make_list_circular DD imagerel $LN5
	DD	imagerel $LN5+98
	DD	imagerel $unwind$make_list_circular
$pdata$print_list DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$print_list
$pdata$search_list DD imagerel $LN6
	DD	imagerel $LN6+79
	DD	imagerel $unwind$search_list
$pdata$delete_first_value_matching_node DD imagerel $LN9
	DD	imagerel $LN9+205
	DD	imagerel $unwind$delete_first_value_matching_node
$pdata$delete_all_value_matching_nodes DD imagerel $LN9
	DD	imagerel $LN9+168
	DD	imagerel $unwind$delete_all_value_matching_nodes
$pdata$is_list_circular DD imagerel $LN6
	DD	imagerel $LN6+119
	DD	imagerel $unwind$is_list_circular
pdata	ENDS
xdata	SEGMENT
$unwind$create_node DD 010801H
	DD	06208H
$unwind$add_to_list DD 010d01H
	DD	0620dH
$unwind$make_list_circular DD 010901H
	DD	06209H
$unwind$print_list DD 010901H
	DD	06209H
$unwind$search_list DD 010d01H
	DD	0220dH
$unwind$delete_first_value_matching_node DD 010d01H
	DD	0820dH
$unwind$delete_all_value_matching_nodes DD 010d01H
	DD	0420dH
$unwind$is_list_circular DD 010901H
	DD	02209H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
otherListHead$ = 8
otherListUpto$ = 16
create_stack_from_existing_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 166
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 191
	ret	0
create_stack_from_existing_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
fast$ = 0
slow$ = 8
head$ = 32
is_list_circular PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 146
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 147
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR slow$[rsp], rax
; Line 148
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR fast$[rsp], rax
$LN3@is_list_ci:
; Line 149
	cmp	QWORD PTR slow$[rsp], 0
	je	SHORT $LN2@is_list_ci
	cmp	QWORD PTR fast$[rsp], 0
	je	SHORT $LN2@is_list_ci
	mov	rax, QWORD PTR fast$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN2@is_list_ci
	mov	rax, QWORD PTR fast$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN2@is_list_ci
; Line 150
	mov	rax, QWORD PTR fast$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR fast$[rsp], rax
; Line 151
	mov	rax, QWORD PTR slow$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR slow$[rsp], rax
; Line 152
	mov	rax, QWORD PTR fast$[rsp]
	cmp	QWORD PTR slow$[rsp], rax
	jne	SHORT $LN1@is_list_ci
; Line 153
	mov	al, 1
	jmp	SHORT $LN4@is_list_ci
$LN1@is_list_ci:
; Line 155
	jmp	SHORT $LN3@is_list_ci
$LN2@is_list_ci:
; Line 156
	xor	al, al
$LN4@is_list_ci:
; Line 157
	add	rsp, 24
	ret	0
is_list_circular ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
head$ = 8
is_list_empty PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 159
	mov	QWORD PTR [rsp+8], rcx
; Line 160
	cmp	QWORD PTR head$[rsp], 0
	jne	SHORT $LN2@is_list_em
; Line 161
	mov	al, 1
	jmp	SHORT $LN3@is_list_em
; Line 162
	jmp	SHORT $LN1@is_list_em
$LN2@is_list_em:
; Line 163
	xor	al, al
$LN1@is_list_em:
$LN3@is_list_em:
; Line 164
	ret	0
is_list_empty ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
isDeleted$ = 0
curr$ = 8
prev$ = 16
head$ = 48
val$ = 56
delete_all_value_matching_nodes PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 121
$LN9:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 122
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR prev$[rsp], rax
; Line 123
	mov	QWORD PTR curr$[rsp], 0
; Line 124
	mov	BYTE PTR isDeleted$[rsp], 0
; Line 125
	mov	rax, QWORD PTR head$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN6@delete_all
; Line 126
	mov	rax, QWORD PTR head$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
$LN5@delete_all:
; Line 127
	cmp	QWORD PTR curr$[rsp], 0
	je	SHORT $LN4@delete_all
; Line 128
	mov	rax, QWORD PTR curr$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN3@delete_all
; Line 129
	mov	BYTE PTR isDeleted$[rsp], 1
; Line 130
	mov	rax, QWORD PTR prev$[rsp]
	mov	rcx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax+8], rcx
$LN3@delete_all:
; Line 133
	mov	rax, QWORD PTR curr$[rsp]
	mov	QWORD PTR prev$[rsp], rax
; Line 134
	mov	rax, QWORD PTR curr$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
; Line 135
	jmp	SHORT $LN5@delete_all
$LN4@delete_all:
; Line 137
	jmp	SHORT $LN2@delete_all
$LN6@delete_all:
; Line 138
	mov	rax, QWORD PTR prev$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN1@delete_all
; Line 139
	mov	BYTE PTR isDeleted$[rsp], 1
; Line 140
	mov	QWORD PTR prev$[rsp], 0
$LN1@delete_all:
$LN2@delete_all:
; Line 143
	movzx	eax, BYTE PTR isDeleted$[rsp]
; Line 144
	add	rsp, 40					; 00000028H
	ret	0
delete_all_value_matching_nodes ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
isDeleted$ = 32
curr$ = 40
prev$ = 48
head$ = 80
val$ = 88
delete_first_value_matching_node PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 89
$LN9:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 90
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR prev$[rsp], rax
; Line 91
	mov	QWORD PTR curr$[rsp], 0
; Line 92
	mov	BYTE PTR isDeleted$[rsp], 0
; Line 93
	mov	rax, QWORD PTR head$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN6@delete_fir
; Line 94
	mov	rax, QWORD PTR head$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
; Line 96
	lea	rcx, OFFSET FLAT:$SG4543
	call	printf
$LN5@delete_fir:
; Line 98
	cmp	QWORD PTR curr$[rsp], 0
	je	SHORT $LN4@delete_fir
	movzx	eax, BYTE PTR isDeleted$[rsp]
	test	eax, eax
	jne	SHORT $LN4@delete_fir
; Line 99
	mov	rax, QWORD PTR curr$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN3@delete_fir
; Line 100
	mov	rax, QWORD PTR prev$[rsp]
	mov	rcx, QWORD PTR curr$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	QWORD PTR [rax+8], rcx
; Line 101
	mov	BYTE PTR isDeleted$[rsp], 1
$LN3@delete_fir:
; Line 104
	mov	rax, QWORD PTR curr$[rsp]
	mov	QWORD PTR prev$[rsp], rax
; Line 105
	mov	rax, QWORD PTR curr$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR curr$[rsp], rax
; Line 106
	jmp	SHORT $LN5@delete_fir
$LN4@delete_fir:
; Line 108
	jmp	SHORT $LN2@delete_fir
$LN6@delete_fir:
; Line 110
	lea	rcx, OFFSET FLAT:$SG4550
	call	printf
; Line 112
	mov	rax, QWORD PTR prev$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN1@delete_fir
; Line 113
	mov	BYTE PTR isDeleted$[rsp], 1
; Line 115
	mov	QWORD PTR prev$[rsp], 0
$LN1@delete_fir:
$LN2@delete_fir:
; Line 118
	movzx	eax, BYTE PTR isDeleted$[rsp]
; Line 119
	add	rsp, 72					; 00000048H
	ret	0
delete_first_value_matching_node ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
isFound$ = 0
start$ = 8
head$ = 32
val$ = 40
search_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 76
$LN6:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 77
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR start$[rsp], rax
; Line 78
	mov	BYTE PTR isFound$[rsp], 0
$LN3@search_lis:
; Line 79
	cmp	QWORD PTR start$[rsp], 0
	je	SHORT $LN2@search_lis
; Line 80
	mov	rax, QWORD PTR start$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	cmp	DWORD PTR [rax], ecx
	jne	SHORT $LN1@search_lis
; Line 81
	mov	BYTE PTR isFound$[rsp], 1
; Line 82
	jmp	SHORT $LN2@search_lis
$LN1@search_lis:
; Line 84
	mov	rax, QWORD PTR start$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR start$[rsp], rax
; Line 85
	jmp	SHORT $LN3@search_lis
$LN2@search_lis:
; Line 86
	movzx	eax, BYTE PTR isFound$[rsp]
; Line 87
	add	rsp, 24
	ret	0
search_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 32
head$ = 64
print_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 50
$LN9:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 52
	lea	rcx, OFFSET FLAT:$SG4504
	call	printf
; Line 54
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR ptr$[rsp], rax
; Line 55
	mov	rcx, QWORD PTR head$[rsp]
	call	is_list_circular
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN6@print_list
; Line 56
	lea	rcx, OFFSET FLAT:$SG4507
	call	printf
; Line 58
	jmp	SHORT $LN5@print_list
$LN6@print_list:
; Line 59
	cmp	QWORD PTR ptr$[rsp], 0
	je	SHORT $LN4@print_list
; Line 60
	lea	rcx, OFFSET FLAT:$SG4511
	call	printf
$LN3@print_list:
; Line 61
	cmp	QWORD PTR ptr$[rsp], 0
	je	SHORT $LN2@print_list
; Line 62
	mov	r8, QWORD PTR ptr$[rsp]
	mov	rax, QWORD PTR ptr$[rsp]
	mov	edx, DWORD PTR [rax]
	lea	rcx, OFFSET FLAT:$SG4515
	call	printf
; Line 63
	mov	rax, QWORD PTR ptr$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR ptr$[rsp], rax
; Line 64
	jmp	SHORT $LN3@print_list
$LN2@print_list:
; Line 65
	lea	rcx, OFFSET FLAT:$SG4516
	call	printf
; Line 67
	jmp	SHORT $LN1@print_list
$LN4@print_list:
; Line 68
	lea	rcx, OFFSET FLAT:$SG4518
	call	printf
$LN1@print_list:
$LN5@print_list:
; Line 72
	lea	rcx, OFFSET FLAT:$SG4519
	call	printf
; Line 74
	add	rsp, 56					; 00000038H
	ret	0
print_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tmp$ = 32
head$ = 64
make_list_circular PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 36
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 38
	lea	rcx, OFFSET FLAT:$SG4495
	call	printf
; Line 40
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR tmp$[rsp], rax
$LN2@make_list_:
; Line 41
	cmp	QWORD PTR tmp$[rsp], 0
	je	SHORT $LN1@make_list_
	mov	rax, QWORD PTR tmp$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN1@make_list_
; Line 42
	mov	rax, QWORD PTR tmp$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR tmp$[rsp], rax
; Line 43
	jmp	SHORT $LN2@make_list_
$LN1@make_list_:
; Line 44
	mov	rax, QWORD PTR tmp$[rsp]
	mov	rcx, QWORD PTR head$[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 46
	lea	rcx, OFFSET FLAT:$SG4500
	call	printf
; Line 48
	add	rsp, 56					; 00000038H
	ret	0
make_list_circular ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tmp$ = 32
newTS$ = 40
head$ = 64
val$ = 72
add_to_list PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 21
$LN5:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 23
	mov	edx, DWORD PTR val$[rsp]
	lea	rcx, OFFSET FLAT:$SG4484
	call	printf
; Line 25
	mov	ecx, DWORD PTR val$[rsp]
	call	create_node
	mov	QWORD PTR newTS$[rsp], rax
; Line 26
	mov	rax, QWORD PTR head$[rsp]
	mov	QWORD PTR tmp$[rsp], rax
$LN2@add_to_lis:
; Line 27
	mov	rax, QWORD PTR tmp$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN1@add_to_lis
; Line 28
	mov	rax, QWORD PTR tmp$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR tmp$[rsp], rax
; Line 29
	jmp	SHORT $LN2@add_to_lis
$LN1@add_to_lis:
; Line 30
	mov	rax, QWORD PTR tmp$[rsp]
	mov	rcx, QWORD PTR newTS$[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 32
	lea	rcx, OFFSET FLAT:$SG4491
	call	printf
; Line 34
	add	rsp, 56					; 00000038H
	ret	0
add_to_list ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 32
val$ = 64
create_node PROC
; File c:\src\blog posts\linked lists\integer linked list.c
; Line 4
$LN4:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 6
	mov	edx, DWORD PTR val$[rsp]
	lea	rcx, OFFSET FLAT:$SG4471
	call	printf
; Line 8
	mov	ecx, 16
	call	malloc
	mov	QWORD PTR ptr$[rsp], rax
; Line 9
	cmp	QWORD PTR ptr$[rsp], 0
	jne	SHORT $LN1@create_nod
; Line 10
	call	abort
$LN1@create_nod:
; Line 12
	mov	rax, QWORD PTR ptr$[rsp]
	mov	ecx, DWORD PTR val$[rsp]
	mov	DWORD PTR [rax], ecx
; Line 13
	mov	rax, QWORD PTR ptr$[rsp]
	mov	QWORD PTR [rax+8], 0
; Line 15
	mov	rax, QWORD PTR ptr$[rsp]
	jmp	SHORT $LN2@create_nod
; Line 17
	lea	rcx, OFFSET FLAT:$SG4478
	call	printf
$LN2@create_nod:
$LN3@create_nod:
; Line 19
	add	rsp, 56					; 00000038H
	ret	0
create_node ENDP
_TEXT	ENDS
END
