; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60610.1 

	TITLE	d:\source\blog posts\linked lists\linked list runner.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG4313	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4314	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4315	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4316	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4317	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4318	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4319	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4320	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4321	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4322	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4323	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
	ORG $+2
$SG4324	DB	0aH, 0aH, 'Firing test %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_fireTests
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	_TEST_should_setup_and_confim_via_printing:PROC
EXTRN	_TEST_should_find_number_in_list:PROC
EXTRN	_TEST_should_not_find_number_in_list:PROC
EXTRN	_TEST_should_delete_numbers_first_occurence:PROC
EXTRN	_TEST_should_delete_all_occurences_on_a_number:PROC
EXTRN	_TEST_shoud_not_be_a_circular_list:PROC
EXTRN	_TEST_shoud_be_a_circular_list:PROC
EXTRN	_TEST_stack_should_be_reverse_of_the_list:PROC
EXTRN	_TEST_should_make_a_circular_list_acircular:PROC
EXTRN	_TEST_should_add_node_at_beginning_of_list:PROC
EXTRN	_TEST_should_add_node_at_end_of_list:PROC
EXTRN	_TEST_should_add_node_at_mid_of_list:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File d:\source\blog posts\linked lists\linked list runner.c
; Line 31
	push	ebp
	mov	ebp, esp
; Line 32
	call	_fireTests
; Line 33
	xor	eax, eax
; Line 34
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_fireTests PROC
; File d:\source\blog posts\linked lists\linked list runner.c
; Line 3
	push	ebp
	mov	ebp, esp
; Line 4
	push	1
	push	OFFSET $SG4313
	call	_printf
	add	esp, 8
; Line 5
	call	_TEST_should_setup_and_confim_via_printing
; Line 6
	push	2
	push	OFFSET $SG4314
	call	_printf
	add	esp, 8
; Line 7
	call	_TEST_should_find_number_in_list
; Line 8
	push	3
	push	OFFSET $SG4315
	call	_printf
	add	esp, 8
; Line 9
	call	_TEST_should_delete_numbers_first_occurence
; Line 10
	push	4
	push	OFFSET $SG4316
	call	_printf
	add	esp, 8
; Line 11
	call	_TEST_should_delete_all_occurences_on_a_number
; Line 12
	push	5
	push	OFFSET $SG4317
	call	_printf
	add	esp, 8
; Line 13
	call	_TEST_shoud_not_be_a_circular_list
; Line 14
	push	6
	push	OFFSET $SG4318
	call	_printf
	add	esp, 8
; Line 15
	call	_TEST_shoud_be_a_circular_list
; Line 16
	push	7
	push	OFFSET $SG4319
	call	_printf
	add	esp, 8
; Line 17
	call	_TEST_should_not_find_number_in_list
; Line 18
	push	8
	push	OFFSET $SG4320
	call	_printf
	add	esp, 8
; Line 19
	call	_TEST_stack_should_be_reverse_of_the_list
; Line 20
	push	9
	push	OFFSET $SG4321
	call	_printf
	add	esp, 8
; Line 21
	call	_TEST_should_make_a_circular_list_acircular
; Line 22
	push	10					; 0000000aH
	push	OFFSET $SG4322
	call	_printf
	add	esp, 8
; Line 23
	call	_TEST_should_add_node_at_beginning_of_list
; Line 24
	push	11					; 0000000bH
	push	OFFSET $SG4323
	call	_printf
	add	esp, 8
; Line 25
	call	_TEST_should_add_node_at_mid_of_list
; Line 26
	push	12					; 0000000cH
	push	OFFSET $SG4324
	call	_printf
	add	esp, 8
; Line 27
	call	_TEST_should_add_node_at_end_of_list
; Line 29
	pop	ebp
	ret	0
_fireTests ENDP
_TEXT	ENDS
END
